# Copyright 2017 the Heptio Ark contributors.
#
# Popular example from velero tweaked to deploy in OpenShift
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-example
  labels:
    app: nginx

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-logs
  namespace: nginx-example
  labels:
    app: nginx
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""  
  resources:
    requests:
      storage: 50Mi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-html
  namespace: nginx-example
  labels:
    app: nginx
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "glusterfs-storage"
  resources:
    requests:
      storage: 50Mi

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-example
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: nginx-logs
          persistentVolumeClaim:
           claimName: nginx-logs
        - name: nginx-html
          persistentVolumeClaim:
           claimName: nginx-html
      containers:
      - image: docker.io/twalter/openshift-nginx
        name: nginx
        ports:
        - containerPort: 8081
        volumeMounts:
          - mountPath: "/var/log/nginx"
            name: nginx-logs
            readOnly: false
          - mountPath: "/usr/share/nginx/html"
            name: nginx-html
            readOnly: true

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: my-nginx
  namespace: nginx-example
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: nginx
  type: LoadBalancer

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: my-nginx
  namespace: nginx-example
  labels:
    app: nginx
    service: my-nginx
spec:
  to:
    kind: Service
    name: my-nginx
  port:
    targetPort: 8081

