apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: datagrid-cronjob
message: |-
  Creates a cronjob to insert data in a datagrid cache

objects:
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    name: ${CRON_NAME}
    labels:
      application: ${CRON_NAME}
  spec:
    schedule: "*/1 * * * *"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              application: ${CRON_NAME}
          spec:
            containers:
            - name: ${CRON_NAME}
              env:
              - name: CURRENT_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              image: alpine
              args:
              - /bin/sh
              - -c
              -  wget -q -S -O -  https://${DATAGRID_USERNAME}:${DATAGRID_PASSWORD}@${DATAGRID_SERVICE}:8443/rest/${CACHE}/${HOSTNAME}  --no-check-certificate --post-data "${DATA}"
            restartPolicy: OnFailure

parameters:
- description: Name of the cronjob deployed
  displayName: Name
  name: CRON_NAME
  required: true
  value: "insert"
- description: Datagrid service that exposes the datagrid rest api.
  displayName: Datagrid Service
  name: DATAGRID_SERVICE
  required: true
  value: "datagrid-service"
- description: Username used to authenticate in datagrid 
  displayName: Datagrid Username
  name: DATAGRID_USERNAME
  required: true
  value: "test"
- description: Password used to authenticate in datagrid 
  displayName: Datagrid Password
  name: DATAGRID_PASSWORD
  required: true
  value: "changeme"
- description: Name of the cache where the data will be inserted.
  displayName: Cache Name
  name: CACHE
  required: true
  value:  'default'
- description: Username used to authenticate in datagrid 
  displayName: Datagrid Username
  name: DATA
  required: true
  value:  '{ \"namespace\":\"${CURRENT_NAMESPACE}\" }'

