apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: nginx-maxpods-template
message: |-
  Creates a simple nginx app with N replicas

objects:
- apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    labels:
    name: ${NAME}-deployment
  spec:
    replicas: ${REPLICAS}
    template:
      metadata:
        labels:
          app: ${NAME}
      spec:
        containers:
        - image: docker.io/twalter/openshift-nginx
          name: ${NAME}
          ports:
          - containerPort: 8081
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${NAME}
    name: my-${NAME}
  spec:
    ports:
    - port: 8081
      targetPort: 8081
    selector:
      app: ${NAME}
    type: LoadBalancer
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ${NAME}
      service: my-${NAME}
    name: my-${NAME}
  spec:
    port:
      targetPort: 8081
    to:
      kind: Service
      name: my-${NAME}

parameters:
- description: Name used for the application.
  displayName: Name
  name: NAME
  required: true
  value: "nginx"
- description: Number of replicas deployed
  displayName: Replicas
  name: REPLICAS
  required: true
  value: "11"
