apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: hello-cron
message: |-
  Creates a cronjob that says hello every minute using the given image.
objects:
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    name: ${CRON_NAME}
  spec:
    schedule: "*/1 * * * *"
    jobTemplate:
      spec:
        template:
          spec:
            containers:
            - name: ${CRON_NAME}
              env:
              - name: CURRENT_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              image: ${IMAGE}
              args:
              - /bin/sh
              - -c
              -  echo "Hello! from $CURRENT_NAMESPACE"
            restartPolicy: OnFailure

parameters:
- description: Name of the cronjob deployed
  displayName: Name
  name: CRON_NAME
  required: true
  value: "hello-cron"
- description: Image used to say hello
  displayName: Doker Image
  name: IMAGE
  required: true
  value: "alpine"
