
apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: Nooba bucket
message: |-
  Creates a bucket in noobaa using a PVC as Backingstore
objects:
- apiVersion: noobaa.io/v1alpha1
  kind: BackingStore
  metadata:
    finalizers:
    - noobaa.io/finalizer
    labels:
      app: noobaa
    name: mcg-pv-pool-bs
    namespace: ${NAMESPACE}
  spec:
    pvPool:
      numVolumes: 3
      resources:
        requests:
          storage: 50Gi
      storageClass: ${STORAGECLASS}
    type: pv-pool
  
  
- apiVersion: noobaa.io/v1alpha1
  kind: BucketClass
  metadata:
    labels:
      app: noobaa
    name: mcg-pv-pool-bc
    namespace: ${NAMESPACE}
  spec:
    placementPolicy:
      tiers:
      - backingStores:
        - mcg-pv-pool-bs
        placement: Spread
  
  
- apiVersion: objectbucket.io/v1alpha1
  kind: ObjectBucketClaim
  metadata:
    name: mgcbuch
    namespace: ${NAMESPACE}
  spec:
    bucketName: ${BUCKETNAME}
    storageClassName: ${NAMESPACE}.noobaa.io
    additionalConfig:
      bucketclass: mcg-pv-pool-bc


parameters:
- description: Namespace where noobaa is deployed
  displayName: Namespace
  name: NAMESPACE
  required: true
  value: "openshift-storage"
- description: Storageclass used to store the Backingstore
  displayName: Storageclass
  name: STORAGECLASS
  required: true
  value: "gp2"
- description: Namespace of the bucket that will be created
  displayName: Bucket Name
  name: BUCKETNAME
  required: true
  value: "migstorage"
